### ISSUE TITLE
Add zon metadata

### ISSUE THREAD

**Issue by softprops** [RohanVashisht1234/zigistry#2]
Thanks for putting this project together I was going to do something similar a while back. An idea I had at the time was to also parse zon files and highlighting things like dependencies, a sometimes useful inside when shopping for packages to spend on, as well as min supported zig version which is very relevant given stability of one zig version to the next is most often the case a package may not compile unless it supports the version of zig you are using

**Comment by softprops** [comment]
another idea that falls from this. this repo assumes the name of the package is the same as the name of the repo. this is not always the case. however the "name" provided by build.zig.zon would be a better assumptive name of the package as its an explicit declaration of what the author intends the name to be

**Comment by jinzhongjia** [comment]
But there seems to be no perfect solution to parse zon to obtain dependencies.

**Comment by jinzhongjia** [comment]
may be this issue can help:https://github.com/Durobot/zon_get_fields/issues/4

**Comment by RohanVashisht1234** [comment]
Thanks a lot, I am adding this feature soon

**Comment by RohanVashisht1234** [comment]
ok, looks like I need to highlight dependencies, so, in that case, I first need to show repositories that have dependencies like: projects, hence I am making a new page to display all the available Zig projects on Zigistry.

**Comment by RohanVashisht1234** [comment]
Ok, I have added support for dependencies for each package inside the view package details page, hence, I am closing this issue. In the future, I might mention few dependencies names of each repoon the index page, but lets wait for the Zig's zon PR to get merged.
