### ISSUE TITLE
Idea: light theme support?

### ISSUE THREAD

**Issue by jinzhongjia** [RohanVashisht1234/zigistry#3]
The current main color looks a bit too dark during the day, what do you think about adding a brighter color theme?

**Comment by RohanVashisht1234** [comment]
![image](https://github.com/RohanVashisht1234/zigistry/assets/81112205/d1bf63a3-7a19-4b6e-8134-512138383688)

**Comment by RohanVashisht1234** [comment]
Ok, I have added light and dark modes, please tell me if any changes are required.

**Comment by jinzhongjia** [comment]
nice theme! thx
