### ISSUE TITLE
missing packages

### ISSUE THREAD

**Issue by andrewrk** [RohanVashisht1234/zigistry#5]
![image](https://github.com/RohanVashisht1234/zigistry/assets/106511/2b3dc561-fa79-4d56-a8dc-62fb75573814)

however, https://github.com/allyourcodebase/cpython has had the `zig-package` tag since a couple days ago, and your main.json was updated 53 minutes ago.

**Comment by RohanVashisht1234** [comment]
Thanks a lot for mentioning this issue, while researching this issue, I found this [discussion on github](https://github.com/orgs/community/discussions/67194). Which states that GitHub apis doesn't show forked repositories. I have just replied their discussion that we need to add a +fork:true to the api's url to include all the forked repositories.

Currently my program is using:
https://api.github.com/search/repositories?q=topic:zig-package&page=2&per_page=100

And I need to switch it to:
https://api.github.com/search/repositories?q=topic:zig-package+fork:true&page=2&per_page=100

<img width="776" alt="image" src="https://github.com/RohanVashisht1234/zigistry/assets/81112205/897a0540-08ed-497b-9468-b47063e0fbd0">

This will fix the issue.

**Comment by RohanVashisht1234** [comment]
Now, the package is available at https://zigistry.dev/packages/allyourcodebase/cpython
<img width="423" alt="image" src="https://github.com/RohanVashisht1234/zigistry/assets/81112205/e96a40b0-fc50-4f92-bd08-d8204e64a7f2">
