### ISSUE TITLE
feature request: show a lot more packages on the website

### ISSUE THREAD

**Issue by andrewrk** [RohanVashisht1234/zigistry#7]
what is there, like 20 packages on display? how about showing 20,000? I have a scroll bar, you know!

**Comment by RohanVashisht1234** [comment]
Thanks a lot for this suggestion, I have completed this task of implementing an infinite scroll inside of the index page, so that anyone can infinitely scroll and view all the available plugins.

https://github.com/user-attachments/assets/ed420467-9e98-4d08-8985-669735f106ab

**Comment by andrewrk** [comment]
Thank you! It is fun to view the page now :smile:

**Comment by RohanVashisht1234** [comment]
Thanks a lot 👍
